
spring:
  application:
    name: cloud-config-git-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/babybabywang/SpringCloudConfig
          search-paths:
          username:
          password:
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://peer3:8002/eureka/,http://peer2:8001/eureka/,http://peer1:8000/eureka/