spring:
  application:
    name: service-consumer-helloworld
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
server:
  port: 9001
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    resource:
      id: service-consumer-helloworld
      user-info-uri: http://localhost:9999/user
      prefer-token-info: false
