spring:
  application:
    name: service-consumer-helloworld
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
server:
  port: 9001
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    client:
      client-id: client_1
      client-secret: 123
      user-authorization-uri: http://localhost:9999/oauth/authorize
      access-token-uri: http://localhost:9999/oauth/token
      scope: app
    resource:
      jwt:
        key-uri: http://localhost:9999/oauth/token_key