eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

security:
  user:
    password: user
  ignored: /
  sessions: never
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: $$$$$$$$$$$
      client-secret: $$$$$$$$$$$$$$$
      access-token-uri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false