eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
spring:
  redis:
    port: 6379
    host: localhost
  application:
    name: auth-service
server:
  port: 9999
logging:
  level:
    com.huangsm.cloud.cloudeurekaserver.config: debug